### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by MohamadKaramiDarabi** [LouisCAD/Splitties#272] opened 2021-06-25 17:38 UTC
I cant build project. what's the problem? the error is:
Execution failed for task ':modules:mainthread:runCommonizer'.
> Could not resolve all files for configuration ':modules:mainthread:kotlinKlibCommonizerClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-klib-commonizer-embeddable:1.4.10 because no repositories are defined.
     Required by:
         project :modules:mainthread

**Comment by LouisCAD** [comment] 2021-07-16 20:42
Hello, do you still have the issue with the current main branch?

**Comment by MohamadKaramiDarabi** [comment] 2021-07-17 03:12
Hello, yes.

**Comment by LouisCAD** [comment] 2021-07-17 06:08
Which OS are you on?

**Comment by LouisCAD** [comment] 2021-07-17 06:09
Also, can you try opening a fresh clone of the project in IntelliJ IDEA 2021.2 EAP? Community Edition will work fine if you don't have Ultimate.

**Comment by MohamadKaramiDarabi** [comment] 2021-07-17 06:12
Linux

**Comment by MohamadKaramiDarabi** [comment] 2021-07-17 12:50
Hello, can you recommended a good book to learn Gradle?

**Comment by LouisCAD** [comment] 2021-07-17 14:31
I'm closing this issue because of lack of information on how to reproduce it. The project (latest revision of the `main` branch) builds fine on Linux in CI, and on Windows and macOS as well, in fact, most of the artifacts of the library are built and published from Linux (Ubuntu 20.04).

**Closed by LouisCAD** 2021-07-17 14:31 UTC
Labels: Waiting for reply

**Comment by MohamadKaramiDarabi** [comment] 2021-07-17 16:47
Thank you. Its work well in windows.
