### ISSUE TITLE
Splitties does not work with compose

### ISSUE THREAD

**Issue by Ashanen** [LouisCAD/Splitties#237] opened 2020-05-03 13:56 UTC
I have a project build in splitties and I wanted to test out jetpack compose. After adding :    

```
buildFeatures {
        compose = true
    }
```
I get a code generation error "

> e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
> Element is unknownThe root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:42) [...]

Is there any way to fix it?

**Comment by LouisCAD** [comment] 2020-05-06 20:58
Hello, I could say the issue is more the reverse, compose not supporting Splitties, but even that wouldn't be accurate either.
Compose is not even at alpha stage (while Splitties is 🙃), and more importantly, it is using an incomplete but newer compiler version to interface with it. It being incomplete means that you can get such errors.

I'm closing this issue as it is not related to Splitties, but if once Compose uses a proper Kotlin version (instead of a fork), there's still an issue, please open a new issue, providing evidence of it being caused by Splitties, and a link to the kotl.in/issue otherwise.

**Closed by LouisCAD** 2020-05-06 20:58 UTC
